spring:
  datasource: 
    url: jdbc:h2:./h2db/sampledb
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  h2:
    console:
      enabled: true
      path: /console
  thymeleaf:
    cache: false
    check-template-location: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 828269246467-p5e97ndekapgfmrq5a0ai6fe5r35bv63.apps.googleusercontent.com
            client-secret: xRNiaD5ijmsuvUIBTuhbzsio
server:
  port: 8080